// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoKfuM4FwbyGVL8KSQUrEsIVIADDlsCo0',
    appId: '1:332595636354:android:f390d343fcfda864e3ec9b',
    messagingSenderId: '332595636354',
    projectId: 'todo-c8742',
    storageBucket: 'todo-c8742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLmvZck_Rh4zmA8iGFQ9dkALtcRoRQus',
    appId: '1:332595636354:ios:ab575d29addb764ee3ec9b',
    messagingSenderId: '332595636354',
    projectId: 'todo-c8742',
    storageBucket: 'todo-c8742.appspot.com',
    iosClientId: '332595636354-ghuqu9mo6vgaubcud0f761p4mn1131le.apps.googleusercontent.com',
    iosBundleId: 'com.example.sabak33Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY1rCa02Qet87BqfH-A3En08gWdI2g4Eo',
    appId: '1:332595636354:web:a4ea6686690825dde3ec9b',
    messagingSenderId: '332595636354',
    projectId: 'todo-c8742',
    authDomain: 'todo-c8742.firebaseapp.com',
    storageBucket: 'todo-c8742.appspot.com',
  );
}
